### ISSUE TITLE
Not working with electron

### ISSUE THREAD

**Issue by Johnz86** [jduncanator/node-diskusage#17] opened 2017-02-01 08:12 UTC
I tried to use this package in electron application with typescript. It does not work. I get an error:
```
App threw an error during load
Error: The system cannot find message text for message number 0x%1 in the message file for %2.
\\?\C:\GIT\SKBOfflineClientOld_refactored\node_modules\diskusage\build\Release\diskusage.node
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:583:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\GIT\SKBOfflineClientOld_refactored\node_modules\diskusage\index.js:1:93)
```

**Comment by jduncanator** [comment] 2017-02-01 10:31
It looks like the issue is caused by compiling the native module in either x64 when you are running a x86 version of Node, or x86 and running a x64 version of node. As I'm not familiar with the way native modules work with Electron, and nobody else who has been having this issue in other projects have found a solution, I would recommend getting in contact with an Electron developer (maybe just @ tag them here). Happy to work with them to get it working.

That being said, I'll try find out what the issue is myself and push a fix.

**Comment by jduncanator** [comment] 2017-02-01 10:35
@Johnz86 https://github.com/electron/electron/issues/3243 suggests adding the `--dist-url` flag to the `electron-gyp` command. Read through that thread, try what they suggest, and answer back here if it fixes the issue. I'll add it to the README if it does.

**Comment by jduncanator** [comment] 2017-03-05 22:36
I'm setting this as `wontfix` as the original reporter hasn't replied, and fixing issues with Electron modules is out-of-scope.

**Closed by jduncanator** 2017-03-05 22:36 UTC
Labels: wontfix

**Comment by robinwassen** [comment] 2017-07-28 13:10
It is just to run [electron-rebuild](https://github.com/electron/electron-rebuild) on this package to make it work for Electron, which is kind of common when using native modules in Electron.

**Manual command:**
     ./node_modules/.bin/electron-rebuild ./node_modules/diskusage/

**Comment by jacobq** [comment] 2019-04-08 15:58
FWIW, this module appears to work with electron 4.x but runs into trouble when attempting to build for 5.x which uses a newer version of V8. The basic steps to correct this are listed here: https://electronjs.org/blog/nodejs-native-addons-and-electron-5
I haven't verified this for myself, but it looks like this line needs to be updated (and maybe more):

https://github.com/jduncanator/node-diskusage/blob/f113dab18cd16cfc33cefdd468b7dd143e31a291/src/main.cpp#L37
