### ISSUE TITLE
Cannot install diskuasge package with node v12.3.0 and npm v6.14.2

### ISSUE THREAD

**Issue by PrashanthGowda** [jduncanator/node-diskusage#50] opened 2020-03-18 06:45 UTC
I have a problem installing diskusage package v1.1.3 with node v12.3.0 and npm v6.14.2, i am getting the error as given below,

```npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! diskusage@1.1.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the diskusage@1.1.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.```

with node v10 I am not getting this error. 

I am working on windows 10 platform.

**Comment by noahbjohnson** [comment] 2020-03-26 04:24
Could this be a duplicate of #41 ?

**Comment by Shadowlong** [comment] 2020-08-31 06:21
same problem on MacOS node -v v14.8.0

**Comment by jduncanator** [comment] 2023-09-15 10:54
This should be resolved with the latest release, if you're still having issues, please let me know.

**Closed by jduncanator** 2023-09-15 10:54 UTC
